production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: learn_rails
  username: <%= Rails.application.secrets.database['username'] %>
  password: <%= Rails.application.secrets.database['password'] %>
  host: <%= Rails.application.secrets.database['host'] %>
  port: <%= Rails.application.secrets.database['port'] %>

development:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: learn_rails_development
  username: <%= Rails.application.secrets.database['username'] %>
  password: <%= Rails.application.secrets.database['password'] %>
  host: <%= Rails.application.secrets.database['host'] %>
  port: <%= Rails.application.secrets.database['port'] %>

test:
  adapter: mysql2
  encoding: utf8
  pool: 5
  database: learn_rails_test
  username: <%= Rails.application.secrets.database['username'] %>
  password: <%= Rails.application.secrets.database['password'] %>
  host: <%= Rails.application.secrets.database['host'] %>
  port: <%= Rails.application.secrets.database['port'] %>
